### ISSUE TITLE
 Le texte des emails est toujours buggé (envoie le mauvais email) 2/2

### ISSUE THREAD

**Issue by bmaz** [medialab/resin-formulaire#10]
Voici ce que les admin reçoivent lorsque quelqu'un modifie son profil

Bonjour,

Votre profil a bien été mis à jour sur l'annuaire RésIn.

Merci beaucoup pour l'intérêt que vous portez à notre initiative.
N'hésitez pas à en parler autour de vous.

Merci et à bientôt,
L'équipe de l'annuaire RésIn

**Comment by jillro** [comment]
Fixed by https://github.com/medialab/resin-api/commit/64bb4c2e66b3593964764b32533537da399c4a95
