### ISSUE TITLE
Request Entity Too Large when sending the form

### ISSUE THREAD

**Issue by bmaz** [medialab/resin-formulaire#11]
[Error] Failed to load resource: the server responded with a status of 413 (Request Entity Too Large) (members, line 0)

**Comment by jillro** [comment]
Probablement quelque chose qui se configure côté NGINX (qui par défaut bloque les requêtes POST de plus de 2 mo).

**Comment by bmaz** [comment]
> Probablement quelque chose qui se configure côté NGINX (qui par défaut bloque les requêtes POST de plus de 2 mo).

C'était bien ça, merci !
