### ISSUE TITLE
Le texte des emails est toujours buggé  (envoie localhost) 1/2

### ISSUE THREAD

**Issue by bmaz** [medialab/resin-formulaire#9]
Bonjour,

Vous pouvez éditer votre profil sur l'annuaire RésIn grâce à ce lien : http://localhost:3000/s-inscrire?uid=6&token=c1994bbf97c51d31366b3e1f170b54ac744ce425
Attention, ce dernier n'est valable que 24h.

N'hésitez pas à nous contacter pour toute information.

Merci et à bientôt,
L'équipe de l'annuaire RésIn

**Comment by jillro** [comment]
J'ai l'impression que vous n'avez pas configuré `RESIN_EDIT_PROFILE_URL` ?
